language: node_js
node_js:
  - "8"
cache: yarn
before_script: npm run compile
env:
  - secure: oM7/cioG6m6BtlvVEak8lDOtoVdwo4YVk7/Ew8Pe3/ubLBtpY7rKi2hgzCmGWCa3LpkxTexQ+MJNSdd+2hsQx0uPMPgolF4VYM+zuH1lVOHWYIN1tOkSug4BegKNR/SRhu4wHmosE6ulCQIYsh9HA2A0YSXeJeCG5SglRP6znbpsIDmd//iLS3RvQPcdovKEa0rbQkot0DUR+bCuMghbNexNzzH1IOIygox1McJ4SMsIw/kDfqasJbLn7PFtWJbeBCo2Qs2tgYc3Hl5eXqpgBwvhNKAolvqxJGzeOGC7w6fK2X6PTy9C3h3OZWuF6DLKiOtezvizQsH0k+wPiGWMbXspZfLv3rr6iAxbkH4lsgHZ3nYR6TMPjsdhD4IcQKfsAIRvF4xMgHMSQeSrrkmQau0u1iHethlxMyd7WoCuLGs873V0ToQ8P4a1BwHEB9ZDGAqoPL3uqCrHv5ykjMdBPgERacGbt7828f2TfcA4sBrpfAOp/PyZMTFxPhR/1dbissSbtzNMSS73fxRsGqK3IHD9q2JllGX5s7LbGxHwwHX1RBEfLyRfqQG5udK8/QQjzTxEhQ4I3UqEi2PDCtOupdWvd9uFfvS2SeCkYACqP7YOq5YWncH4ARpOCHcvtgmecqQLEcC4rshziGtWOXLInKmXHLN04MMT+KB9ooPojUU=
jobs:
  include:
    - stage: Compile
      script: npm run compile
    - stage: Test
      script:
        - npm run test:js
        - npm run test:only
    - stage: Publish
      deploy:
        provider: script
        on:
          tags: true
        script: npx vsce publish -p $AZURE_TOKEN
